on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
            node-version: 19

      - uses: pnpm/action-setup@v2
        with:
            version: 8

      - run: pnpm install
      - run: pnpm build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 2deb019ec6ccde3dc86b061c443293d3
          projectName: jimcomputer
          directory: dist
